version: '3'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/usr/src/app/corner/app
    ports:
      - '8098:3000'
    restart: always
    depends_on:
      - graphql
    networks:
      - corner-networks
    environment:
      - TZ=Asia/Hong_Kong
    command: sh -c "npm install --legacy-peer-deps && npm run dev"

  # api:
  #   container_name: api
  #   restart: always
  #   build: ./api
  #   ports:
  #     # - '80:3000'
  #     - '1003:3000'
  #   links:
  #     - mongo
  #     - crawler
  #   volumes:
  #     - ./api:/usr/src/app/api
  #   networks:
  #     - corner-networks
  mongo:
    container_name: corner_mongo
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./mongo:/usr/src/app/corner/mongo
    networks:
      - corner-networks
    environment:
      - TZ=Asia/Hong_Kong
  crawler:
    restart: always
    build: ./crawler
    command: sh -c "npm install && npm run start"
    working_dir: /usr/src/app/corner/crawler
    ports: 
      - '2002:8082'
    volumes:
      - ./crawler:/usr/src/app/corner/crawler
    networks:
      - corner-networks
    environment:
      - TZ=Asia/Hong_Kong
  api:
    restart: always
    build: ./api
    command: sh -c "npm install && npm run start"
    working_dir: /usr/src/app/corner/api
    ports: 
      - '2003:8083'
    volumes:
      - ./api:/usr/src/app/corner/api
    networks:
      - corner-networks
    environment:
      WAIT_HOSTS: mongo:27017

  graphql:
    restart: always
    build: ./graphql
    command: sh -c "npm install && npm run start"
    working_dir: /usr/src/app/corner/graphql
    ports: 
      - '2004:8084'
    volumes:
      - ./graphql:/usr/src/app/corner/graphql
    networks:
      - corner-networks
    environment:
      WAIT_HOSTS: mongo:27017

networks:
  corner-networks:
    driver: bridge
