schema {
  query: Query
}

type Match {
  id: ID
  winId: String
  matchNum: String
  matchDatetime(format: DatetimeFormatEnum): Date
  matchDay: String
  ended: Boolean
  homeTeam: Team
  awayTeam: Team
  league: League
  history: MatchHistory
  result: Result
  odds(type: OddTypeEnum, orderBy: OrderByEnum, limit: Int): Odds
}

type MatchHistory {
  home: [Match]
  away: [Match]
}

type Query {
  match(id: ID!): Match
}
