type Odds {
  HAD: [HAD]
  HHA: [HHA]
  FHA: [FHA]
  HIL: [HIL]
  FHL: [FHL]
  HDC: [HDC]
  CHL: [CHL]
  FAKE_HDC: FAKE_HDC
}

type FAKE_HDC {
  value: String
  isFake: Boolean
}

type HAD {
  H: String
  A: String
  D: String
  datetime(format: DatetimeFormatEnum): Date
}

type HHA {
  H: String
  A: String
  D: String
  HG: String
  AG: String
  datetime(format: DatetimeFormatEnum): Date
}

type FHA {
  H: String
  A: String
  D: String
  HG: String
  AG: String
  datetime(format: DatetimeFormatEnum): Date
}

type HDC {
  H: String
  A: String
  HG: String
  AG: String
  datetime(format: DatetimeFormatEnum): Date
}

type HIL {
  H: String
  L: String
  LINE: String
  datetime(format: DatetimeFormatEnum): Date
}

type FHL {
  H: String
  L: String
  LINE: String
  datetime(format: DatetimeFormatEnum): Date
}

type CHL {
  H: String
  L: String
  LINE: String
  datetime(format: DatetimeFormatEnum): Date
}
