type Team {
  teamId: String
  teamName: String
  winId: String
  image: String
  history(
    leagueId: String
    after: String
    before: String
    teamId: String
  ): [Match]
}

type Query {
  team(id: ID, name: String): Team @cacheControl(maxAge: 30)
}
