type Query {
  tips(days: Int): [Tip]
}

type Tip {
  match: Match
  betType: String
  betItem: String
  betOdd: String
  betGrade: String
  betLine: String
  isStarted: String
  gainLost: Float
  date: String
  result: String
}

type TipsMatch {
  match: Match
  stat: TipsMatchStat
}

type TipsMatchStat {
  home: TipsMatchStatDetail
  away: TipsMatchStatDetail
}

type TipsMatchStatDetail {
  CHL: TipsMatchStatCHL
  HIL: TipsMatchStatHIL
}

type TipsMatchStatCHL {
  H: Int
  L: Int
  percent: Float
}

type TipsMatchStatHIL {
  H: Int
  L: Int
  percent: Float
}
