scalar Date

enum DatetimeFormatEnum {
  DEFAULT
  UNIX
  FULL_FORMATTED
  HH_mm
  DD_MM
  DD
}

enum OddTypeEnum {
  FULL
  FIRST_LATEST
  FIRST
  LATEST
}

enum OrderByEnum {
  DESC
  ASC
}

type Pagination {
  totalDocs: Int
  limit: Int
  totalPages: Int
  page: Int
  pagingCounter: Int
  hasPrevPage: Boolean
  hasNextPage: Boolean
  prevPage: Int
  nextPage: Int
}

enum CacheControlScope {
  PUBLIC
  PRIVATE
}

directive @cacheControl(
  maxAge: Int
  scope: CacheControlScope
) on FIELD_DEFINITION | OBJECT | INTERFACE
