query match($id: ID!) {
  match(id: $id) {
    ...match
    history {
      home {
        ...match
      }
      away {
        ...match
      }
    }
  }
}

fragment match on Match {
  id
  matchDatetime(format: FULL_FORMATTED)
  matchDate: matchDatetime(format: DD_MM)
  ended
  homeTeam {
    teamId
    teamName
    rank
  }
  awayTeam {
    teamId
    teamName
    rank
  }
  league {
    leagueId
    name
  }
  ...odds_firstlatest
  ...result
}

fragment result on Match {
  result {
    FT {
      home
      away
    }
    HT {
      home
      away
    }
    corner {
      full {
        total
        home
        away
      }
      half {
        total
        home
        away
      }
    }
    HAD
    FHA
    HHA {
      first
      latest
    }
    HDC {
      first
      latest
    }
    HIL {
      first
      latest
    }
    FHL {
      first
      latest
    }
    CHL {
      first
      latest
    }
  }
}

fragment odds_firstlatest on Match {
  odds(type: FIRST_LATEST) {
    HAD {
      H
      D
      A
    }
    FHA {
      H
      D
      A
    }
    HHA {
      H
      D
      A
      HG
      AG
    }
    HDC {
      H
      A
      HG
      AG
    }
    HIL {
      H
      L
      LINE
    }
    FHL {
      H
      L
      LINE
    }
    CHL {
      H
      L
      LINE
    }
  }
}
